trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn build
  displayName: 'Install dependencies and build'

- script: |
    yarn test
  displayName: 'Run tests'

- script: |
    yarn lint
  displayName: 'Run linting'

- script: |
    yarn format
  displayName: 'Run code formatting'